name: ktools
description: A command-line tool for generating Dart code from assets and translations.
repository: https://github.com/kalucky0/ktools
version: 1.1.0

environment:
  sdk: ^3.4.0

dependencies: 
  yaml: ^3.1.2
  class_generator: ^2.0.1

dev_dependencies:
  lints: ^4.0.0
