name: ktools
description: A command-line tool for generating classes from assets
repository: https://github.com/kalucky0/ktools
version: 1.0.0

environment:
  sdk: ^3.3.1

dependencies: 
  yaml: ^3.1.2
  class_generator: ^2.0.1

dev_dependencies:
  lints: ^3.0.0
